config/routes.rb
Rails.application.routes.draw do
  get 'foods/index'

  get 'foods/show'

  get 'categories/index'

  get 'categories/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'war' => 'site#war'
  get 'menu' => 'site#menu'
  get 'about' => 'site#about'
  get 'burger_builder' => 'site#burger_builder'
  root 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
    @cat = Category.find(params[:id])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
  end

  def show
    @food = Food.find(params[:id])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @cats = Category.all
  end

  def war
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>
<% @cats.each do |cat| %>
  <%= cat.name %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @cat.name %></h1>

<% @cat.foods.each do |food| %>
  <%= link_to "#{food.name}", foods_show_path(id: food.id) %>
  <br>
  <%= "$" + food.price %>
  <br>
  <%= food.description %>
  <br>
  <%= image_tag("#{food.image_url}", size: "100x100" ) %>
  <p>----------------------</p>
<% end %>

app/views/foods/index.html.erb
<h1>Foods#index</h1>
<p>Find me in app/views/foods/index.html.erb</p>

app/views/foods/show.html.erb
<h1><%= @food.name %></h1>
<%= image_tag("#{@food.image_url}", size: "200x200" ) %>
<p><%= @food.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bears Burgers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-container">
       <figure>
         <%= image_tag('bearsburgerslogo.svg', class: 'header-img') %>
         <figcaption><strong>Better food. Better people.</strong></figcaption>
       </figure>
     </div>
     <nav>
       <%= link_to 'Home', root_url %>
       <%= link_to 'About', about_url %>
       <%= link_to 'Menu', menu_url %>
       <%= link_to 'Burger Builder', burger_builder_url %>
     </nav>
   </header>
     <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/site/burger_builder.html.erb
<h2>Burger Builder</h2>
<div>
  <h3>Step 1 - <em>Pick a bun</em></h3>
  <section class="burger-section">
    <div class="menu-item">
      <%= image_tag("brioche.png", class: 'menu bread') %>
      <p>Brioche</p>
    </div>
    <div class="menu-item">
      <%= image_tag("pretzel.png", class: 'menu bread') %>
      <p>Prezel</p>
    </div>
  </section>
  <h3>Step 2 - <em>Pick a patty</em></h3>
  <section class="burger-section">

  </section>
  <h3>Step 3 - <em>Pick your toppings</em></h3>
  <section class="burger-section">
    <div class="menu-item">
      <%= image_tag("avocado.png", class: 'menu topping') %>
      <p>Avocado</p>
    </div>
    <div class="menu-item">
      <%= image_tag("red-onion.png", class: 'menu topping') %>
      <p>Red Onion</p>
    </div>
    <div class="menu-item">
      <%= image_tag("mushrooms.png", class: 'menu topping') %>
      <p>Sliced Mushrooms</p>
    </div>
  </section>
</div>
<div class="builder">
  <h5>Your burger:</h5>
</div>
<svg class='vegan veg' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256.8 250.5"><path d="M59.4 0.5c5.3-0.5 10.5-0.9 16 0 3.1 0.6 6.2 1 9.2 1.9 13.8 3.8 25.6 10.8 34.6 22.1 3.3 4.2 6.3 8.8 9.6 13.5 0.5-1 1-2 1.5-2.9 9-16.1 22.5-26.8 40.1-32.2 3.6-1.1 7.4-1.6 11.1-2.4 5.5-0.5 9.5-0.8 16 0 1.9 0.4 3.9 0.6 5.8 1.1C218 5 230.5 12.1 240.5 23.8c6.9 8.1 11.8 17.2 14.2 27.6 0.6 2.7 1.2 5.5 1.8 8.2 0.6 5 0.4 10.4-0.4 15.9 -2.2 13.6-8.2 25.5-16.4 36.3 -10.1 13.3-20.7 26.3-31.1 39.5 -12.6 16-25.3 32-37.9 48.1 -13.4 17.1-26.8 34.2-40.2 51.3 -0.3 0-0.7 0-1 0 -8.8-11-17.7-22-26.5-33 -14.7-18.2-29.6-36.3-44.3-54.5 -11.7-14.5-23.2-29.1-35-43.5 -11-13.4-19.8-27.7-23.2-45 -0.7-5-0.3-9.8 0-15 0.4-1.9 0.7-3.9 1.1-5.8C4.8 38.9 12 26.4 23.7 16.4 31.8 9.5 40.9 4.7 51.2 2.3 54 1.7 56.7 1.1 59.4 0.5zM81.5 50.1c-13.6 0-27 0-40.9 0 0.7 1.4 1.1 2.4 1.7 3.4 28.5 53.8 57 107.6 85.5 161.4 0.1 0.1 0.2 0.2 0.4 0.2 0.2 0 0.3 0 0.8 0 29-54.8 58.1-109.7 87.4-165 -14.2 0-27.6 0-41.1 0 -1.4 3-2.7 5.9-4.1 8.7 -5.8 11.6-11.6 23.1-17.3 34.7 -7.9 16.1-15.8 32.2-23.7 48.3 -0.4 0.8-1.1 1.4-2.1 2.5C112.3 112.6 96.9 81.4 81.5 50.1z"></path></svg>
<svg class='vegetarian veg' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 135.1 157.3"><path d="M132.5 63.8c-4.7-20.7-12.2-40.3-23.5-58.4 -1.3-2.1-3.4-4-5-5.4 -0.7 0.5-1.5 1.9-1.8 2.8 -6.4 14.8-12.6 29.6-17.7 44.9 -4 12-7.7 24-9.2 36.5 4.8 5.3 8.1 11.2 10.5 17.6 2.4 6.5 3.2 13.3 4.2 20.2 8.2-22.7 12.7-46.1 15.1-69.9 6 35.7 4.4 70.1-17.1 101.9 24.8-9.8 38.9-27.4 44.8-52.4C135.4 90.7 136.3 79 132.5 63.8z"></path><path d="M50.7 73.1C34.8 64.5 17.7 59.5 0 56c0 0.7 6.9 17.9 10 25.7 7.4 18.9 12.9 33.9 25.7 49.9 8.1 10 23.7 28.1 42.3 25.4 -11.5-30.3-23.6-48-40.9-68.9 0.9-0.4 11.2 6.4 15.7 10.4 11.2 9.8 21 20.8 28.7 34 0.5-0.9 0.9-1.4 1.1-2 2.6-10.5 2-20.7-3.3-30.4C72.8 87.9 62.7 79.4 50.7 73.1z"></path></svg>

app/views/site/index.html.erb
<h1>Hello World</h1>
<% @cats.each do |cat| %>
  <%= link_to "#{cat.name}", categories_show_path(id: cat.id) %>
  <br>
<% end %>

app/views/site/menu.html.erb
<h1>Our Menu</h1>
<section>
  <h3>Starters</h3>
  <div class="menu-item">
    <h5>Guac Platter</h5>
    <p>Guacamole made fresh daily with Hass avocados, freshly squeezed lime juice, roma tomatoes, jalapen&#771;os, red onions, and sea salt. Topped with cojita cheese and a balsamic glaze.</p>
  </div>
  <div class="menu-item">
    <h5>Baked Buffalo Cauliflower</h5>
    <p>Cauliflower baked at 350F then tossed in buffalo sauce. Served with herb ranch.</p>
  </div>
  <div class="menu-item">
    <h5>Nachos</h5>
    <p>Made with Stone Ground Corn tortilla chips, black been puree&#769, fresh cut Cilantro, </p>
  </div>
</section>
<section>
  <h3>Sides</h3>
  <div class="menu-item">
    <h5>Baked Herb and Parmesan Fries</h5>
    <p>Idaho potatoes soaked and cut daily, tossed in italian herbs and parmesan, roasted at 350F. Served with Herb Ranch.</p>
  </div>
  <div class="menu-item">
    <h5>Baked Sweet Potato Fries</h5>
    <p></p>
  </div>
</section>
<section>
  <h3>Burgers</h3>

</section>
<section>
  <h3>Other Sandwiches</h3>
  <div class="burger-item">
    <h5>Toasted Peanut Butter &amp; Jelly</h5>
    <p>Choose from Grape, Raspberry, and Strawberry jellies. Substitute Almond Butter upon request.</p>
  </div>
</section>
<section>
  <h3>Other Entrees</h3>
  <div class="burger-item">
    <h5>Tofu Stir Fry</h5>
    <p>Brown rice. Tossed in a Thai-style peanut sauce.</p>
  </div>
  <div class="burger-item">
    <h5>Red Quinoa Chili</h5>
    <p></p>
  </div>
</section>
<section>
  <h3>Greens &amp; Salads</h3>

</section>
<section>
  <h3>Sauces</h3>
  <h6>All sauces are made in-house</h6>
  <p>Herb Ranch</p>
  <p>Honey Mustard</p>
  <p>BBQ Sauce</p>
  <p>Cajun Mayo</p>
  <p>Garlic Mayo</p>
</section>
<section>
  <h3>Sweets</h3>
  <div class="burger-item">
    <h5>Chocolate PB Balls</h5>
    <p>Peanut butter covered in dark chocholate. Dusted in sea salt and served cold.</p>
  </div>
</section>
<section>
  <section>
    <h3></h3>

  </section>
</section>

app/views/site/war.html.erb
<h1>WaR is coming!</h1>